/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'tenant-users': TenantUserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    'tenant-users': TenantUser;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'tenant-users': TenantUsersSelect<false> | TenantUsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (TenantUser & {
        collection: 'tenant-users';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface TenantUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  /**
   * Platform-level role (only superadmin supported currently)
   */
  role?: 'superadmin' | null;
  /**
   * Account status of the admin
   */
  status?: ('active' | 'inactive') | null;
  /**
   * Timestamp of last successful login
   */
  lastLoginAt?: string | null;
  /**
   * Soft deletion timestamp
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Short or trading name of the company
   */
  companyName: string;
  /**
   * Full registered legal name of the company
   */
  fullName?: string | null;
  /**
   * Australian Business Number (if applicable)
   */
  abn?: string | null;
  /**
   * Australian Company Number (if applicable)
   */
  acn?: string | null;
  /**
   * Official company website URL
   */
  website?: string | null;
  /**
   * Standard Carrier Alpha Code (used for identifying carriers)
   */
  scac?: string | null;
  emails?: {
    /**
     * Account/Finance department email
     */
    account?: string | null;
    /**
     * Bookings department email
     */
    bookings?: string | null;
    /**
     * Management email
     */
    management?: string | null;
    /**
     * Operations department email
     */
    operations?: string | null;
    /**
     * Reply-to email address
     */
    replyTo?: string | null;
  };
  address?: {
    /**
     * Street address
     */
    street?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State/Province
     */
    state?: string | null;
    /**
     * Postal/ZIP code
     */
    postalCode?: string | null;
    /**
     * Country code (e.g., AU, US)
     */
    countryCode?: string | null;
  };
  /**
   * Primary business contact number
   */
  phone?: string | null;
  /**
   * Company fax number (optional)
   */
  fax?: string | null;
  /**
   * General company email or contact address
   */
  email: string;
  /**
   * Company logo file
   */
  logo?: (number | null) | Media;
  /**
   * Dedicated subdomain for the tenant (e.g., abc.truckingapp.com)
   */
  subdomain?: string | null;
  /**
   * Whether the tenant has been approved by an admin
   */
  approved?: boolean | null;
  /**
   * Reference to the approving super admin
   */
  approvedBy?: (number | null) | User;
  /**
   * Whether company info and documents are verified
   */
  verified?: boolean | null;
  /**
   * Timestamp when verification was completed
   */
  verifiedAt?: string | null;
  /**
   * Indicates acceptance of privacy terms
   */
  privacyConsent?: boolean | null;
  /**
   * When terms and conditions were accepted
   */
  termsAcceptedAt?: string | null;
  emailPreferences?: {
    /**
     * Receive marketing emails
     */
    marketing?: boolean | null;
    /**
     * Receive product updates
     */
    updates?: boolean | null;
    /**
     * Receive system notifications
     */
    system?: boolean | null;
  };
  /**
   * Data hosting region
   */
  dataRegion?: ('ap-southeast-2' | 'us-east-1' | 'eu-central-1') | null;
  /**
   * Track onboarding progress (draft/submitted/backoffice)
   */
  onboardingStep?: string | null;
  /**
   * Soft delete timestamp
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-users".
 */
export interface TenantUser {
  id: number;
  /**
   * Links user to their company (tenant)
   */
  tenantId: number | Tenant;
  /**
   * User's chosen username (unique within tenant)
   */
  username?: string | null;
  /**
   * Full name of the user
   */
  fullName: string;
  /**
   * Mobile contact number
   */
  phoneMobile?: string | null;
  /**
   * Fixed-line phone number
   */
  phoneFixed?: string | null;
  /**
   * Direct Dial-In extension (optional)
   */
  ddi?: string | null;
  /**
   * Job title or position in the company
   */
  position?: string | null;
  /**
   * Role or group the user belongs to
   */
  userGroup?: ('Admin' | 'Dispatcher' | 'Driver' | 'Manager') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'tenant-users';
        value: number | TenantUser;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'tenant-users';
        value: number | TenantUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'tenant-users';
        value: number | TenantUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  status?: T;
  lastLoginAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  companyName?: T;
  fullName?: T;
  abn?: T;
  acn?: T;
  website?: T;
  scac?: T;
  emails?:
    | T
    | {
        account?: T;
        bookings?: T;
        management?: T;
        operations?: T;
        replyTo?: T;
      };
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        countryCode?: T;
      };
  phone?: T;
  fax?: T;
  email?: T;
  logo?: T;
  subdomain?: T;
  approved?: T;
  approvedBy?: T;
  verified?: T;
  verifiedAt?: T;
  privacyConsent?: T;
  termsAcceptedAt?: T;
  emailPreferences?:
    | T
    | {
        marketing?: T;
        updates?: T;
        system?: T;
      };
  dataRegion?: T;
  onboardingStep?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-users_select".
 */
export interface TenantUsersSelect<T extends boolean = true> {
  tenantId?: T;
  username?: T;
  fullName?: T;
  phoneMobile?: T;
  phoneFixed?: T;
  ddi?: T;
  position?: T;
  userGroup?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}