/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'tenant-users': TenantUserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    'tenant-users': TenantUser;
    'tenant-roles': TenantRole;
    customers: Customer;
    'handling-units': HandlingUnit;
    'storage-units': StorageUnit;
    skus: Skus;
    'paying-customers': PayingCustomer;
    warehouses: Warehouse;
    'transport-companies': TransportCompany;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'tenant-users': TenantUsersSelect<false> | TenantUsersSelect<true>;
    'tenant-roles': TenantRolesSelect<false> | TenantRolesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'handling-units': HandlingUnitsSelect<false> | HandlingUnitsSelect<true>;
    'storage-units': StorageUnitsSelect<false> | StorageUnitsSelect<true>;
    skus: SkusSelect<false> | SkusSelect<true>;
    'paying-customers': PayingCustomersSelect<false> | PayingCustomersSelect<true>;
    warehouses: WarehousesSelect<false> | WarehousesSelect<true>;
    'transport-companies': TransportCompaniesSelect<false> | TransportCompaniesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (TenantUser & {
        collection: 'tenant-users';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface TenantUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  /**
   * Platform-level role (only superadmin supported currently)
   */
  role?: 'superadmin' | null;
  /**
   * Account status of the admin
   */
  status?: ('active' | 'inactive') | null;
  /**
   * Timestamp of last successful login
   */
  lastLoginAt?: string | null;
  /**
   * Soft deletion timestamp
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Short or trading name of the company
   */
  companyName: string;
  /**
   * Full registered legal name of the company
   */
  fullName?: string | null;
  /**
   * Australian Business Number (if applicable)
   */
  abn?: string | null;
  /**
   * Australian Company Number (if applicable)
   */
  acn?: string | null;
  /**
   * Official company website URL
   */
  website?: string | null;
  /**
   * Standard Carrier Alpha Code (used for identifying carriers)
   */
  scac?: string | null;
  emails?: {
    /**
     * Account/Finance department email
     */
    account?: string | null;
    /**
     * Bookings department email
     */
    bookings?: string | null;
    /**
     * Management email
     */
    management?: string | null;
    /**
     * Operations department email
     */
    operations?: string | null;
    /**
     * Reply-to email address
     */
    replyTo?: string | null;
  };
  address?: {
    /**
     * Street address
     */
    street?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State/Province
     */
    state?: string | null;
    /**
     * Postal/ZIP code
     */
    postalCode?: string | null;
    /**
     * Country code (e.g., AU, US)
     */
    countryCode?: string | null;
  };
  /**
   * Primary business contact number
   */
  phone?: string | null;
  /**
   * Company fax number (optional)
   */
  fax?: string | null;
  /**
   * General company email or contact address
   */
  email: string;
  /**
   * Company logo file
   */
  logo?: (number | null) | Media;
  /**
   * Dedicated subdomain for the tenant (e.g., abc.truckingapp.com)
   */
  subdomain?: string | null;
  /**
   * Whether the tenant has been approved by an admin
   */
  approved?: boolean | null;
  /**
   * Reference to the approving super admin
   */
  approvedBy?: (number | null) | User;
  /**
   * Whether company info and documents are verified
   */
  verified?: boolean | null;
  /**
   * Timestamp when verification was completed
   */
  verifiedAt?: string | null;
  /**
   * Indicates acceptance of privacy terms
   */
  privacyConsent?: boolean | null;
  /**
   * When terms and conditions were accepted
   */
  termsAcceptedAt?: string | null;
  emailPreferences?: {
    /**
     * Receive marketing emails
     */
    marketing?: boolean | null;
    /**
     * Receive product updates
     */
    updates?: boolean | null;
    /**
     * Receive system notifications
     */
    system?: boolean | null;
  };
  /**
   * Data hosting region
   */
  dataRegion?: ('ap-southeast-2' | 'us-east-1' | 'eu-central-1') | null;
  /**
   * Track onboarding progress (draft/submitted/backoffice)
   */
  onboardingStep?: string | null;
  /**
   * Current status of the tenant request
   */
  status?: ('pending' | 'needs_correction' | 'approved' | 'rejected') | null;
  /**
   * Token for editing tenant details (used for correction requests)
   */
  editToken?: string | null;
  /**
   * Expiration date for the edit token
   */
  editTokenExpiresAt?: string | null;
  /**
   * Reason for requesting corrections from the tenant
   */
  revertReason?: string | null;
  /**
   * Soft delete timestamp
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-users".
 */
export interface TenantUser {
  id: number;
  /**
   * Links user to their company (tenant)
   */
  tenantId: number | Tenant;
  /**
   * User's chosen username (unique within tenant)
   */
  username?: string | null;
  /**
   * Full name of the user
   */
  fullName: string;
  /**
   * Mobile contact number
   */
  phoneMobile?: string | null;
  /**
   * Fixed-line phone number
   */
  phoneFixed?: string | null;
  /**
   * Direct Dial-In extension (optional)
   */
  ddi?: string | null;
  /**
   * Job title or position in the company
   */
  position?: string | null;
  /**
   * Role assigned to the user
   */
  role: number | TenantRole;
  /**
   * DEPRECATED: Use role field instead. This field is kept for backward compatibility.
   */
  userGroup?: ('Admin' | 'Dispatcher' | 'Driver' | 'Manager') | null;
  /**
   * User account status
   */
  status?: ('active' | 'suspended') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-roles".
 */
export interface TenantRole {
  id: number;
  /**
   * Name of the role (unique per tenant)
   */
  name: string;
  /**
   * Optional description of the role
   */
  description?: string | null;
  /**
   * Tenant this role belongs to
   */
  tenantId: number | Tenant;
  /**
   * System roles (like Admin) cannot be edited or deleted
   */
  isSystemRole?: boolean | null;
  permissions?: {
    /**
     * View dashboard
     */
    dashboard_view?: boolean | null;
    /**
     * Edit dashboard
     */
    dashboard_edit?: boolean | null;
    /**
     * View containers
     */
    containers_view?: boolean | null;
    /**
     * Create containers
     */
    containers_create?: boolean | null;
    /**
     * Edit containers
     */
    containers_edit?: boolean | null;
    /**
     * Delete containers
     */
    containers_delete?: boolean | null;
    /**
     * View inventory
     */
    inventory_view?: boolean | null;
    /**
     * Create inventory
     */
    inventory_create?: boolean | null;
    /**
     * Edit inventory
     */
    inventory_edit?: boolean | null;
    /**
     * Delete inventory
     */
    inventory_delete?: boolean | null;
    /**
     * View transportation
     */
    transportation_view?: boolean | null;
    /**
     * Create transportation
     */
    transportation_create?: boolean | null;
    /**
     * Edit transportation
     */
    transportation_edit?: boolean | null;
    /**
     * Delete transportation
     */
    transportation_delete?: boolean | null;
    /**
     * View live map
     */
    map_view?: boolean | null;
    /**
     * Edit live map
     */
    map_edit?: boolean | null;
    /**
     * View reports
     */
    reports_view?: boolean | null;
    /**
     * Create reports
     */
    reports_create?: boolean | null;
    /**
     * Delete reports
     */
    reports_delete?: boolean | null;
    /**
     * View settings
     */
    settings_view?: boolean | null;
    /**
     * Manage tenant users
     */
    settings_manage_users?: boolean | null;
    /**
     * Manage roles
     */
    settings_manage_roles?: boolean | null;
    /**
     * Manage entity settings
     */
    settings_entity_settings?: boolean | null;
    /**
     * Manage user settings
     */
    settings_user_settings?: boolean | null;
    /**
     * Manage personalization
     */
    settings_personalization?: boolean | null;
  };
  /**
   * Whether this role is active
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  /**
   * Links customer to their company (tenant)
   */
  tenantId: number | Tenant;
  /**
   * Name of delivery customer or consignee/consignor
   */
  customer_name: string;
  /**
   * Customer email address
   */
  email?: string | null;
  /**
   * Primary contact name
   */
  contact_name?: string | null;
  /**
   * Contact phone number
   */
  contact_phone?: string | null;
  /**
   * Street address
   */
  street?: string | null;
  /**
   * City
   */
  city?: string | null;
  /**
   * State or province
   */
  state?: string | null;
  /**
   * Postal/ZIP code
   */
  postcode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "handling-units".
 */
export interface HandlingUnit {
  id: number;
  /**
   * Links handling unit to their company (tenant)
   */
  tenantId: number | Tenant;
  /**
   * Short code for the unit (e.g. CTN for carton)
   */
  abbreviation?: string | null;
  /**
   * Full name of handling unit (e.g. Carton, Bottle, Drum)
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-units".
 */
export interface StorageUnit {
  id: number;
  /**
   * Links storage unit to their company (tenant)
   */
  tenantId: number | Tenant;
  /**
   * Short code for storage unit (e.g. PAL for pallet)
   */
  abbreviation?: string | null;
  /**
   * Full name of storage unit (e.g. Pallet, Rack)
   */
  name: string;
  /**
   * Number of pallet spaces this unit occupies
   */
  palletSpaces?: number | null;
  /**
   * Length per storage unit in millimeters
   */
  lengthPerSU_mm?: number | null;
  /**
   * Width per storage unit in millimeters
   */
  widthPerSU_mm?: number | null;
  /**
   * Basis for warehouse storage charging
   */
  whstoChargeBy?: ('LPN' | 'weight' | 'cubic' | 'sqm') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skus".
 */
export interface Skus {
  id: number;
  /**
   * Links SKU to their company (tenant)
   */
  tenantId: number | Tenant;
  /**
   * Unique SKU identifier for product
   */
  skuCode: string;
  /**
   * Detailed product description
   */
  description?: string | null;
  /**
   * Customer who owns or is linked to this SKU
   */
  customerId?: (number | null) | Customer;
  /**
   * Default storage unit (SU) for SKU, mandatory, eg: pallet
   */
  storageUnitId: number | StorageUnit;
  /**
   * Default handling unit (HU) for SKU, mandatory, eg: boxes
   */
  handlingUnitId: number | HandlingUnit;
  /**
   * Fetched from selected storage unit
   */
  palletSpacesOfStorageUnit?: number | null;
  /**
   * Number of handling units per storage unit
   */
  huPerSu?: number | null;
  /**
   * Whether SKU can be received per handling unit
   */
  receiveHU?: ('YES' | 'NO') | null;
  /**
   * Whether SKU can be picked per handling unit
   */
  pickHU?: ('YES' | 'NO') | null;
  /**
   * Defines stock picking rule
   */
  pickStrategy?: ('FIFO' | 'FEFO') | null;
  /**
   * Length per handling unit in millimeters
   */
  lengthPerHU_mm?: number | null;
  /**
   * Width per handling unit in millimeters
   */
  widthPerHU_mm?: number | null;
  /**
   * Height per handling unit in millimeters
   */
  heightPerHU_mm?: number | null;
  /**
   * Weight per handling unit in kilograms
   */
  weightPerHU_kg?: number | null;
  /**
   * Number of cases per layer
   */
  casesPerLayer?: number | null;
  /**
   * Number of layers per pallet
   */
  layersPerPallet?: number | null;
  /**
   * Number of cases per pallet
   */
  casesPerPallet?: number | null;
  /**
   * Number of individual units (eachs) per case
   */
  eachsPerCase?: number | null;
  /**
   * Whether expiry date tracking is enabled
   */
  isExpriy?: boolean | null;
  /**
   * Whether attribute 1 is enabled
   */
  isAttribute1?: boolean | null;
  /**
   * Whether attribute 2 is enabled
   */
  isAttribute2?: boolean | null;
  /**
   * Expiry date (optional)
   */
  expiryDate?: string | null;
  /**
   * Extra notes for attribute 1 (optional)
   */
  attribute1?: string | null;
  /**
   * Extra notes for attribute 2 (optional)
   */
  attribute2?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paying-customers".
 */
export interface PayingCustomer {
  id: number;
  /**
   * Links paying customer to their company (tenant)
   */
  tenantId: number | Tenant;
  /**
   * Official name of the paying customer (client responsible for billing)
   */
  customer_name: string;
  /**
   * Business number for invoicing
   */
  abn?: string | null;
  /**
   * Customer email address
   */
  email?: string | null;
  /**
   * Primary contact person for billing
   */
  contact_name?: string | null;
  /**
   * Contact phone number
   */
  contact_phone?: string | null;
  /**
   * Billing street address
   */
  billing_street?: string | null;
  /**
   * Billing city
   */
  billing_city?: string | null;
  /**
   * Billing state or province
   */
  billing_state?: string | null;
  /**
   * Billing postal/ZIP code
   */
  billing_postcode?: string | null;
  /**
   * If true, delivery address = billing address
   */
  delivery_same_as_billing?: boolean | null;
  /**
   * Delivery street address
   */
  delivery_street?: string | null;
  /**
   * Delivery city
   */
  delivery_city?: string | null;
  /**
   * Delivery state or province
   */
  delivery_state?: string | null;
  /**
   * Delivery postal/ZIP code
   */
  delivery_postcode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses".
 */
export interface Warehouse {
  id: number;
  /**
   * Links warehouse to their company (tenant)
   */
  tenantId: number | Tenant;
  /**
   * Name of warehouse or depot
   */
  name: string;
  /**
   * Warehouse email address
   */
  email?: string | null;
  /**
   * Primary contact name
   */
  contact_name?: string | null;
  /**
   * Contact phone number
   */
  contact_phone?: string | null;
  /**
   * Street address
   */
  street?: string | null;
  /**
   * City
   */
  city?: string | null;
  /**
   * State or province
   */
  state?: string | null;
  /**
   * Postal/ZIP code
   */
  postcode?: string | null;
  /**
   * Array of strings for stores in warehouse
   */
  store?:
    | {
        store_name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Differentiates between location types
   */
  type?: ('Depot' | 'Warehouse') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transport-companies".
 */
export interface TransportCompany {
  id: number;
  /**
   * Links transport company to their company (tenant)
   */
  tenantId: number | Tenant;
  /**
   * Third-party transport company name
   */
  name: string;
  /**
   * Primary contact person
   */
  contact?: string | null;
  /**
   * Contact mobile number
   */
  mobile?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'tenant-users';
        value: number | TenantUser;
      } | null)
    | ({
        relationTo: 'tenant-roles';
        value: number | TenantRole;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'handling-units';
        value: number | HandlingUnit;
      } | null)
    | ({
        relationTo: 'storage-units';
        value: number | StorageUnit;
      } | null)
    | ({
        relationTo: 'skus';
        value: number | Skus;
      } | null)
    | ({
        relationTo: 'paying-customers';
        value: number | PayingCustomer;
      } | null)
    | ({
        relationTo: 'warehouses';
        value: number | Warehouse;
      } | null)
    | ({
        relationTo: 'transport-companies';
        value: number | TransportCompany;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'tenant-users';
        value: number | TenantUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'tenant-users';
        value: number | TenantUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  status?: T;
  lastLoginAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  companyName?: T;
  fullName?: T;
  abn?: T;
  acn?: T;
  website?: T;
  scac?: T;
  emails?:
    | T
    | {
        account?: T;
        bookings?: T;
        management?: T;
        operations?: T;
        replyTo?: T;
      };
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        countryCode?: T;
      };
  phone?: T;
  fax?: T;
  email?: T;
  logo?: T;
  subdomain?: T;
  approved?: T;
  approvedBy?: T;
  verified?: T;
  verifiedAt?: T;
  privacyConsent?: T;
  termsAcceptedAt?: T;
  emailPreferences?:
    | T
    | {
        marketing?: T;
        updates?: T;
        system?: T;
      };
  dataRegion?: T;
  onboardingStep?: T;
  status?: T;
  editToken?: T;
  editTokenExpiresAt?: T;
  revertReason?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-users_select".
 */
export interface TenantUsersSelect<T extends boolean = true> {
  tenantId?: T;
  username?: T;
  fullName?: T;
  phoneMobile?: T;
  phoneFixed?: T;
  ddi?: T;
  position?: T;
  role?: T;
  userGroup?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-roles_select".
 */
export interface TenantRolesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  tenantId?: T;
  isSystemRole?: T;
  permissions?:
    | T
    | {
        dashboard_view?: T;
        dashboard_edit?: T;
        containers_view?: T;
        containers_create?: T;
        containers_edit?: T;
        containers_delete?: T;
        inventory_view?: T;
        inventory_create?: T;
        inventory_edit?: T;
        inventory_delete?: T;
        transportation_view?: T;
        transportation_create?: T;
        transportation_edit?: T;
        transportation_delete?: T;
        map_view?: T;
        map_edit?: T;
        reports_view?: T;
        reports_create?: T;
        reports_delete?: T;
        settings_view?: T;
        settings_manage_users?: T;
        settings_manage_roles?: T;
        settings_entity_settings?: T;
        settings_user_settings?: T;
        settings_personalization?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  tenantId?: T;
  customer_name?: T;
  email?: T;
  contact_name?: T;
  contact_phone?: T;
  street?: T;
  city?: T;
  state?: T;
  postcode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "handling-units_select".
 */
export interface HandlingUnitsSelect<T extends boolean = true> {
  tenantId?: T;
  abbreviation?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-units_select".
 */
export interface StorageUnitsSelect<T extends boolean = true> {
  tenantId?: T;
  abbreviation?: T;
  name?: T;
  palletSpaces?: T;
  lengthPerSU_mm?: T;
  widthPerSU_mm?: T;
  whstoChargeBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skus_select".
 */
export interface SkusSelect<T extends boolean = true> {
  tenantId?: T;
  skuCode?: T;
  description?: T;
  customerId?: T;
  storageUnitId?: T;
  handlingUnitId?: T;
  palletSpacesOfStorageUnit?: T;
  huPerSu?: T;
  receiveHU?: T;
  pickHU?: T;
  pickStrategy?: T;
  lengthPerHU_mm?: T;
  widthPerHU_mm?: T;
  heightPerHU_mm?: T;
  weightPerHU_kg?: T;
  casesPerLayer?: T;
  layersPerPallet?: T;
  casesPerPallet?: T;
  eachsPerCase?: T;
  isExpriy?: T;
  isAttribute1?: T;
  isAttribute2?: T;
  expiryDate?: T;
  attribute1?: T;
  attribute2?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paying-customers_select".
 */
export interface PayingCustomersSelect<T extends boolean = true> {
  tenantId?: T;
  customer_name?: T;
  abn?: T;
  email?: T;
  contact_name?: T;
  contact_phone?: T;
  billing_street?: T;
  billing_city?: T;
  billing_state?: T;
  billing_postcode?: T;
  delivery_same_as_billing?: T;
  delivery_street?: T;
  delivery_city?: T;
  delivery_state?: T;
  delivery_postcode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses_select".
 */
export interface WarehousesSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  email?: T;
  contact_name?: T;
  contact_phone?: T;
  street?: T;
  city?: T;
  state?: T;
  postcode?: T;
  store?:
    | T
    | {
        store_name?: T;
        id?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transport-companies_select".
 */
export interface TransportCompaniesSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  contact?: T;
  mobile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}